project:
  type: website

website:
  title: "Tecnofeminismo em ação"
  navbar:
    left:
      - href: index.qmd
        text: Início
      - href: codigo.qmd
        text: Código
      - href: resultados.qmd
        text: Resultados
      - href: imagens.qmd
        text: Visualização


format:
  html:
    theme: cosmo
    toc: true





